// SchemaService: single source of node-parameter typing for the editor.
//
// The schema is the editor-side projection of the Go runtime node definitions
// (generated by haibot/cmd/btschema). It is bundled offline as the
// `nodesSchemaData` Angular value (see schema.data.js); SchemaService caches it
// once in memory [C1] and exposes typed lookups + validation used by the
// schema-driven property panel and the pre-export tree validator.
//
// loadSchema() returns a resolved $q promise so callers can stay async-shaped
// even though the data is already in memory (offline-first, no network) [3.1].
(function() {
  'use strict';

  angular
    .module('app')
    .factory('schemaService', schemaService);

  schemaService.$inject = ['$q', 'parameterTypesValidator', 'nodesSchemaData'];

  function schemaService($q, parameterTypesValidator, nodesSchemaData) {
    var cache = null; // the schema object, loaded once.

    var service = {
      loadSchema          : loadSchema,
      isLoaded            : isLoaded,
      getNodeSchema       : getNodeSchema,
      getParamSchema      : getParamSchema,
      getEnumOptions      : getEnumOptions,
      getEnumLabel        : getEnumLabel,
      validateParam       : validateParam,
      validateNodeParams  : validateNodeParams
    };
    return service;

    // Resolves to the loaded schema object. Caches once; the optional `data`
    // argument lets tests inject an alternate schema.
    function loadSchema(data) {
      if (data) {
        cache = data;
      } else if (!cache) {
        cache = nodesSchemaData || { schemaVersion: 0, nodes: {} };
      }
      // Publish to the non-Angular b3e editor layer so ImportManager can do
      // best-effort data-pin validation. Guarded: b3e may be absent under the
      // headless test shim, in which case validation simply stays disabled.
      if (typeof window !== 'undefined' && window.b3e) {
        window.b3e.schema = cache;
      }
      return $q.when(cache);
    }

    function isLoaded() {
      return cache !== null;
    }

    function _ensure() {
      if (!cache) {
        cache = nodesSchemaData || { schemaVersion: 0, nodes: {} };
      }
      return cache;
    }

    // Returns the NodeSchema for a node type name, or null for unknown/custom
    // nodes (the panel falls back to the generic key-table for those).
    function getNodeSchema(name) {
      if (!name) return null;
      var schema = _ensure();
      if (!schema || !schema.nodes) return null;
      return schema.nodes[name] || null;
    }

    function getParamSchema(name, paramName) {
      var node = getNodeSchema(name);
      if (!node || !node.params) return null;
      for (var i = 0; i < node.params.length; i++) {
        if (node.params[i].name === paramName) return node.params[i];
      }
      return null;
    }

    // Returns the enum options [{value,label}] for an enum param, else [].
    function getEnumOptions(name, paramName) {
      var param = getParamSchema(name, paramName);
      if (param && param.enum && param.enum.options) {
        return param.enum.options;
      }
      return [];
    }

    // Maps a stored numeric enum value back to its label for display.
    function getEnumLabel(name, paramName, value) {
      var options = getEnumOptions(name, paramName);
      var n = typeof value === 'number' ? value : Number(value);
      for (var i = 0; i < options.length; i++) {
        if (options[i].value === n) return options[i].label;
      }
      return String(value);
    }

    // Validates one param value, returns null or an error string.
    function validateParam(name, paramName, value) {
      var param = getParamSchema(name, paramName);
      return parameterTypesValidator.validateParam(param, value);
    }

    // Validates a whole properties object against a node's schema.
    // Returns a map { paramName: errorString } (empty when all valid).
    // Permissive on extra unknown properties for backward compat with old .b3.
    function validateNodeParams(name, props) {
      var errors = {};
      var node = getNodeSchema(name);
      if (!node || !node.params) return errors;
      props = props || {};
      for (var i = 0; i < node.params.length; i++) {
        var param = node.params[i];
        var value = props.hasOwnProperty(param.name) ? props[param.name] : undefined;
        var err = parameterTypesValidator.validateParam(param, value);
        if (err) errors[param.name] = err;
      }
      return errors;
    }
  }
})();
